### ISSUE TITLE
[UPDATE]-[디자인]: 회원가입 디자인 시안 변경에 따라 수정합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#102]
# Task
## feat
- [x] 이메일 블럭 우측 인증번호 확인 버튼 추가
- [x] 서비스 이용약관 자세히 버튼 추가

## fix
- [x] 레이아웃, 컴포넌트 배치 수정
- [x] 전체 서비스 이용약관 노출 제거
- [x] `placeholder` 수정

### 23-05-20
- [x] 인증번호 확인 버튼 배치 수정

### 23-05-27
- [x] 이메일과 인증번호 확인 사이의 `Divider` 제거
- [x] 기존 인증번호 확인 공간 숨김 처리
- [x] 이메일 발송 버튼을 누르고 정상적으로 동작했다면 인증번호 확인 버튼과 공간 보여주기
- [x] Placeholder 문구 수정
