### ISSUE TITLE
[REFACTOR]: 회원가입 페이지를 전반적으로 리팩토링합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#108]
# Task
## refactor
- [x] 기존 `pages`에서 관리하던 `SignUp 컴포넌트`를 `views`에서 관리합니다.
- [x] 컴포넌트 내부에서 작성되던 비즈니스 로직을 `services`에서 관리합니다.
- [x] 타입 `SignUp`을 `전역`으로 관리합니다.
