### ISSUE TITLE
[DESIGN] UI 디자인을 수정합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#127]
# 디자인 수정 사항
- 메인 페이지 메인 배너 이미지 1개가 정해져서 이미지와 제목 수정했고, 메인 배너 이미지는 4개라고 하셔서 배너 안 롤링도 4개로 수정했어요.
- 어바웃 글 행간 조절했고, 배포된 버전 확인해보니 이니셜과 텍스트 윗 상단 맞출 수 있을까요?
- 크리틱 헤어질 결심 이미지 수정했어요.

# Task
- 메인 페이지
  - [x] 배너 이미지와 제목 수정
  - [x] 메인 베너 안 롤링 개수 수정 (4개)
- 어바웃 페이지
  - [x] 글 행간 수정
  - [x] 이니셜과 텍스트 윗 상단 맞추기
- 크리틱 페이지
  ~이미지 수정 (헤어질 결심)~ 서버 데이터에 의존하기로 결정되었습니다.
