### ISSUE TITLE
메인페이지 Recent 게시글 클릭 시 없는 경로로 이동하는 이슈를 수정합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#135]
# Task
- [x] 메인페이지 Recent 게시글 클릭 시, 해당 category 게시글로 이동하도록 수정합니다.
- [x] 필름유니버스 게시판 More을 클릭 시, filmUniverse로 이동하도록 수정합니다.
- [x] Critic 게시판 More 클릭 시, critic으로 이동하도록 수정합니다.

- 이슈
![image](https://github.com/FILMDOM-s/film-doms/assets/84620459/9d4af040-86fd-4821-a948-25ede6ed08ae)
