### ISSUE TITLE
수정 사항에 대응합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#152]
# Task
- [x] 메인 페이지 첫 배너 이미지 클릭 시, Movie 게시판으로 이동합니다.
- [x] 메인 페이지 첫 배너 이미지 텍스트의 간격을 좁힙니다.
- [x] Critic 게시글 작성 시, 사진 3개 이상, 글자 수 3000자 이상 조건이 필요합니다.
- [x] 필름 유니버스 게시글 작성 시, 사진 1개 이상, 지원 및 모집 기간 명시, 모집 기관 이름 및 설명이 필수여야 합니다. -> 모집 기관 이름, 설명 Input이 없음 (제외)
- [x] 푸터 Contact us 클릭 시, 필름덤즈 인스타그램으로 이동합니다.
- [x] 푸터 Follow us의 Twitter와 Facebook을 삭제하고 Threads를 추가합니다.(https://www.threads.net/@filmdomaypole)
- [x] 변경된 토큰 관리 방식을 적용합니다.
  - [x] 비로그인 유저의 접근을 제한합니다. ISSUE #146
- [x] 퍼블릭 프로필 페이지를 구현합니다.
  - [x] 유저 프로필 클릭 시, 해당 페이지로 이동합니다.
- [x] 게시판별, 공지사항 조회 api를 연결합니다. -> recent 404 발생 (제외) ISSUE #147 
- [x] 게시글 검색 시, 인덱스가 맞지 않아 다른 정보가 조회 되는 문제를 해결합니다.
