### ISSUE TITLE
소셜 로그인 관련 이슈들을 처리합니다

### ISSUE THREAD

**Issue by chigomuh** [FILMDOM-s/film-doms#168]
# Task

- [ ] 소셜 로그인 시, 아바타 드롭박스가 표기되지 않던 문제를 해결합니다.
- [ ] 소셜 로그인 시, 추가 정보 기입을 위한 회원가입 폼의 비밀번호, 비밀번호 확인 입력폼을 숨깁니다.
- [ ] 메인 페이지 마지막 배너의 링크를 수정합니다.
